name        : comar-api
version     : 2.4.7
release     : 3
source      :
    - http://evolve-os.com/sources/comar-api-2.4.7.tar.gz : 1f03d0d545c9a66a8631d812d4d02a2fb7e923b2859068f5b0dc49e564c7280e
license     : GPL-2.0
summary     : Utility functions for Comar scripts
description : |
    Generic utility library for common Comar script operations.
setup      : |
    %patch -p1 < $pkgfiles/add-stopdependencies.patch
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
